In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [2]:
api_key = "RGAPI-c6670e3d-3770-49cd-ae8e-293c3f154f31"

from main import PlayerInfo, GameDataGenerator

program = GameDataGenerator(api_key, "WZ802")

list = program.getPlayerMatches()
df = program.getMultipleGameStatsByPlayer(list)
# print(df)

In [3]:
# converts to numpy arrays which are the ideal format for computations
data = np.array(df)

In [4]:
m, n = data.shape
np.random.shuffle(data)

data_dev = data[0:10].T # transposed data to make each example a col instead of a row
Y_dev = data_dev[0]
X_dev = data_dev[1:n]

data_train = data[10:m].T
Y_train = data_train[0]
X_train = data_train[1:n]

In [5]:
print(m, n)

20 7


In [6]:
def init_params():
    
    input_size = 7  # Change this based on your input size
    hidden_layer_size = 10
    output_size = 2  # Change this based on your output size

    W1 = np.random.rand(input_size, hidden_layer_size) - 0.5
    b1 = np.random.rand(hidden_layer_size, 1) - 0.5
    W2 = np.random.rand(hidden_layer_size, output_size) - 0.5
    b2 = np.random.rand(output_size, 1) - 0.5
    
    # W1 = np.random.rand(7, 1) -0.5 # change later
    # b1 = np.random.rand(5, 1) - 0.5
    # W2 = np.random.rand(5, 2) - 0.5
    # b2 = np.random.rand(2, 1) - 0.5
    return W1, b1, W2, b2

def ReLU(Z):
    return np.maximum(0, Z)

def deriv_ReLU(Z):
    return Z > 0

def softmax(Z):
    return np.exp(Z) / np.sum(np.exp(Z))

def forward_prop(W1, b1, W2, b2, X):
    print(W1)
    print(X)
    return

    Z1 = W1.dot(X) + b1
    A1 = ReLU(Z1)
    Z2 = W2.dot(A1) + b2
    A2 = softmax(72)
    return Z1, A1, Z2, A2

# creates the correctly sized output matrix
def one_hot(Y):
    one_hot_Y = np.zeros(Y.size, Y.max() + 1) # in this case 10 outputs
    one_hot_Y[np.arrange(Y.size), Y] = 1
    return one_hot_Y.T

def back_prop(Z1, A1, Z2, A2, W2, X, Y):
    one_hot_Y = one_hot(Y)
    dZ2 = A2 - one_hot_Y
    dW2 = 1 / m * dZ2.dot(A1.T)
    db2 = 1/ m * np.sum(dZ2)
    dZ1 = W2.T.dot(dZ2) * deriv_ReLU(Z1)
    dW1 = 1 / m * dZ1.dot(X.T)
    db1 = 1 / m * np.sum(dZ1, 2)
    return dW1, db1, dW2, db2

def update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha):
    W1 = W1 - alpha * dW1
    b1 = b1 - alpha * db1
    W2 = W2 - alpha * dW2
    b2 = b2 - alpha * db2
    return W1, b1, W2, b2




In [7]:
def get_predictions(A2):
    return np.argmax(A2, 0)

def get_accuracy(predictions, Y):
    print(predictions, Y)
    return np.sum(predictions == Y) / Y.size

def gradient_descent(X, Y, iterations, alpha):
    W1, b1, W2, b2 = init_params()
    for i in range(iterations):
        Z1, A1, Z2, A2 = forward_prop(W1, b1, W2, b2, X)
        break
        dW1, db1, dW2, db2 = back_prop(Z1, A1, Z2, A2, W1, W2, X, Y)
        W1, b1, W2, b2 = update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha)
        
        # for testing: every 10 iterations print accuracy
        if i % 10 == 0:
            print("Iteration: ", i)
            predictions = get_predictions(A2)
            print("Accuracy: " + get_accuracy(predictions, Y))
    return W1, b1, W2, b2


In [8]:
W1, b1, W2, b2 = gradient_descent(X_train, Y_train, 10, 0.1)
print(X_train)


[[ 0.06967634 -0.40918477  0.14436558 -0.45935219  0.20755821  0.31777007
  -0.27321538  0.35567816  0.1836338   0.09251797]
 [ 0.02608043  0.10715366 -0.17273338  0.08214047  0.46601107 -0.2471944
  -0.40301884 -0.11879287 -0.45576967 -0.41164908]
 [ 0.27090223  0.35697048 -0.41782906 -0.48713722  0.05809118 -0.31646901
  -0.41710767  0.20899428 -0.13039199  0.14831121]
 [-0.07814553  0.31116732 -0.10724567 -0.39881572 -0.07019555  0.43733402
   0.12627902  0.33482751  0.11993382 -0.15908306]
 [ 0.42563194 -0.30810106 -0.39372353  0.19741404 -0.00979853  0.27767049
   0.39513143  0.1325062   0.11783492 -0.49389569]
 [-0.33015906 -0.01176111 -0.08906966  0.42342385  0.45371062 -0.02157455
  -0.14523438  0.19409369 -0.17513515  0.37914088]
 [-0.30059126  0.00194107 -0.48011816  0.19391123  0.26197664 -0.41941181
   0.13089327  0.06881242  0.25535051 -0.25545778]]
[[2172 1901 2041 2335 293 1690 2044 1901 1733 1849]
 [5 6 7 13 0 6 8 3 3 2]
 [8 4 4 8 0 8 5 2 7 11]
 [8 7 7 15 0 9 12 5 9 9]


TypeError: cannot unpack non-iterable NoneType object